services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: payohada-backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f","http://localhost:8000"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    expose:
      - "8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}  
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
    networks:
      - payohada-test

#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    container_name: payohada-frontend
#    restart: unless-stopped
#    env_file:
#      - ./frontend/.env 
#      - .env
    
  caddy:
    image: caddy 
    expose:
      - 80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./frontend/dist:/srv
    develop:
      watch:
        - action: sync+restart 
          path: ./frontend/dist 
          target: /srv
    networks:
      - payohada-test

