services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: payohada-backend
    restart: unless-stopped
    expose:
      - "8000"
    env_file:
      - ./backend/.env
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - HOST=0.0.0.0
      - PORT=8000
    profiles:
      - production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: payohada-frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env 
      - .env
    
  caddy:
    image: caddy 
    expose:
      - 80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./frontend/dist:/srv
    profiles:
      - production


