-- ==============================================================================
-- SEED DE LA BASE DE DONNEES PAYOHADA (POSTGRESQL / SQLITE)
-- ==============================================================================

-- 1. Seed de la table constantes
INSERT INTO constantes (code, description, montant, unite, pays) VALUES
('C_NBHTRA_REF', 'NOMBRE D''HEURES TRAVAILLEES DE REFERENCE', 173.33, NULL, 'CI'),
('C_NBJRTRA_REF', 'NOMBRE DE JOURS TRAVAILLES DE REFERENCE', 30.00, NULL, 'CI'),
('CE_EXP_REG_GL', 'Contribution employeur expatrié regime général', 11.50, NULL, 'CI'),
('CE_REG_AG', 'Contribution employeur régime agricole', 2.00, NULL, 'CI'),
('CN_REG_GL', 'Contribution nationale régime général', 1.50, NULL, 'CI'),
('FDFP_TA', 'FDFP Taxe apprentissage', 0.40, NULL, 'CI'),
('FDFP_TFC', 'FDFP Taxe formation continue', 0.60, NULL, 'CI'),
('MAX_MUGEFCI', 'COTISATION MAXIMUM MUGEFCI', 0.00, NULL, 'CI'),
('MOD_CONV_H_J', 'Mode de conversion des heures travaillés en jours', 0.00, NULL, 'CI'),
('MONT_COT_CMU', 'Montant cotisation CMU', 1000.00, NULL, 'CI'),
('PL_LG_INDTRANS', 'Plancher légal de l''indemnité de transport', 30000.00, NULL, 'CI'),
('PL_LG_PRIM_SALI', 'Plancher légal de la prime de salissure', 4500.00, NULL, 'CI'),
('PL_LG_PRIMOUTIL', 'Plancher légal de la prime d''outillage', 3461.00, NULL, 'CI'),
('PL_LG_PRIMTENUE', 'Plancher légal de la prime de tenue de travail', 2423.00, NULL, 'CI'),
('PLF_AT_AM_PF', 'Montant plafond PF, ATMP et AM', 75000.00, NULL, 'CI'),
('PLF_AT_AM_PF_H', 'Montant plafond PF, ATMP et AM Horaire', 433.00, NULL, 'CI'),
('PLF_AT_AM_PF_J', 'Montant plafond PF, ATMP et AM journalier', 3462.00, NULL, 'CI'),
('PLF_AV', 'Montant plafond Assurance vieillesse', 3375000.00, NULL, 'CI'),
('PLF_AV_H', 'Plafond assurance vieillesse horaire', 19472.00, NULL, 'CI'),
('PLF_AV_J', 'Plafond assurance vieillesse journalier', 155772.00, NULL, 'CI'),
('PLF_INDEM_APPR', 'Plafond indemnité d''apprentissage', 100000.00, NULL, 'CI'),
('PLF_INDEM_STAGE', 'Montant plafond indemnité de stage', 150000.00, NULL, 'CI'),
('PLF_JR_HR', 'Montant plafond journalier et horaire', 3231.00, NULL, 'CI'),
('PLF_MUGEFCI', 'PLAFOND MUGEFCI', 0.00, NULL, 'CI'),
('PRIM_LG_PANIER', 'Prime légale de panier', 1038.00, NULL, 'CI'),
('SMIG', 'SMIG mensuel', 75000.00, NULL, 'CI'),
('SMIG_H', 'SMIG horaire', 433.00, NULL, 'CI'),
('SMIG_J', 'SMIG journalier', 3462.00, NULL, 'CI'),
('TAUX_AM', 'Taux assurance maternité', 0.75, NULL, 'CI'),
('TAUX_AT', 'Taux accident de travail', 2.00, NULL, 'CI'),
('TAUX_AV', 'Taux assurance vieillesse', 7.70, NULL, 'CI'),
('TAUX_BNC', 'TAUX_BNC', 3.50, NULL, 'CI'),
('TAUX_CGRAE_E', 'TAUX CGRAE PART EMPLOYE', 8.33, NULL, 'CI'),
('TAUX_CGRAE_P', 'TAUX CGRAE PART PATRONALE', 16.67, NULL, 'CI'),
('TAUX_HS_100', 'TAUX HEURE SUPPLEMENTAIRE 100%', 2.00, NULL, 'CI'),
('TAUX_HS_15', 'TAUX HEURE SUPPLEMENTAIRE 15%', 1.15, NULL, 'CI'),
('TAUX_HS_50', 'TAUX HEURE SUPPLEMENTAIRE 50%', 1.50, NULL, 'CI'),
('TAUX_HS_75', 'TAUX HEURE SUPPLEMENTAIRE 75%', 1.75, NULL, 'CI'),
('TAUX_HS_N', 'TAUX HEURE SUPPLEMENTAIRE NORMALE', 1.00, NULL, 'CI'),
('TAUX_JRSUP_NORM', 'Taux normal jours supplémentaires', 1.00, NULL, 'CI'),
('TAUX_MUGEFCI', 'TAUX DE COTISATION MUGEFCI', 0.00, NULL, 'CI'),
('TAUX_PF', 'Taux prestation familiale', 5.00, NULL, 'CI'),
('TAUX_PRIM_PRECA', 'Taux de la prime de précarité', 5.00, NULL, 'CI'),
('TAUXIS', 'TAUX IS', 1.20, NULL, 'CI'),
('TAUXRET', 'TAUXRET', 6.30, NULL, 'CI'),
('TAXAPP', 'Taxe d''apprentissage', 0.40, NULL, 'CI'),
('TAXFORM', 'Taxe Formation continue', 0.60, NULL, 'CI'),
('VAL_INDICE', 'VALEUR INDICIAIRE', 233.46, NULL, 'CI')
ON CONFLICT (code, pays) DO UPDATE SET
  description = EXCLUDED.description,
  montant = EXCLUDED.montant,
  unite = EXCLUDED.unite,
  date_modification = CURRENT_TIMESTAMP;

-- 2. Seed de la table plan_paie
INSERT INTO plan_paie (code, type, libelle, mode_calcul, sens, pays) VALUES
('BASE', 'B', 'Salaire de base', 'Manuel', 'Gain', 'CI'),
('SURSALAIRE', 'B', 'Sursalaire', 'Manuel', 'Gain', 'CI'),
('ABS', 'B', 'Absence', 'Sémi-auto', 'Retenue', 'CI'),
('HS_15', 'B', 'Heures supplémentaires majorées à 15%', 'Sémi-auto', 'Gain', 'CI'),
('HS_25', 'B', 'Heures supplémentaires majorées à 25%', 'Sémi-auto', 'Gain', 'CI'),
('HS_50', 'B', 'Heures supplémentaires majorées à 50%', 'Sémi-auto', 'Gain', 'CI'),
('IBS', 'I', 'Impôt brut sur salaire', 'Auto', 'Retenue', 'CI'),
('RICF', 'I', 'Réduction d''impôt pour charge familiale', 'Auto', 'Gain', 'CI'),
('CNPS_PF', 'I', 'CNPS - Prestations Familiales', 'Auto', 'Retenue', 'CI'),
('CNPS_RETRAITE', 'I', 'CNPS - Retraite', 'Auto', 'Retenue', 'CI'),
('CNPS_AT', 'I', 'CNPS - Accidents du Travail et Maladies Pro.', 'Auto', 'Retenue', 'CI'),
('CNPS_MATERNITE', 'I', 'CNPS - Assurance Maternité', 'Auto', 'Retenue', 'CI'),
('CMU_S', 'I', 'Cotisation CMU part salariale', 'Auto', 'Retenue', 'CI'),
('CMU_P', 'C', 'Cotisation CMU part patronale', 'Auto', 'Charge', 'CI'),
('CN', 'C', 'Contribution nationale', 'Auto', 'Charge', 'CI'),
('TA', 'C', 'Taxe d''apprentissage', 'Auto', 'Charge', 'CI'),
('TFC', 'C', 'Taxe Formation continue', 'Auto', 'Charge', 'CI'),
('TRANSPORT', 'A', 'Indemnité de transport', 'Sémi-auto', 'Gain', 'CI'),
('TELEPHONE', 'A', 'Dotation téléphonique', 'Sémi-auto', 'Gain', 'CI')
('B', '1001', 'Salaire de base', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1051', 'Sursalaire', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1091', 'Prime d anciennete', 'Auto', 'Gain', FALSE, TRUE, '661200', NULL, 'CI'),
('B', '1101', 'Heures supplementaires taux normal', 'Auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1111', 'Heures supplementaires a 15%', 'Auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1121', 'Heures supplementaires a 50%', 'Auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1131', 'Heures supplementaires a 75%', 'Auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1141', 'Heures supplementaires a 100%', 'Auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1151', 'Jours supplementaires taux normal', 'Auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1161', 'Heure supplementaire', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1181', 'Heures complementaires', 'Auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1201', 'Prime de panier', 'Semi-auto', 'Gain', FALSE, TRUE, '661200', NULL, 'CI'),
('B', '1211', 'Prime de salissure', 'Semi-auto', 'Gain', FALSE, TRUE, '661200', NULL, 'CI'),
('B', '1221', 'Prime de Tenue de travail', 'Semi-auto', 'Gain', FALSE, TRUE, '661200', NULL, 'CI'),
('B', '1231', 'Prime d outillage', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1241', 'Indemnite d equipement', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1251', 'Indemnite d expatriation', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1301', 'Indemnite de fonction', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1311', 'Indemnite de representation', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1321', 'Indemnite de responsabilite', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1401', 'Indemnite de logement', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1411', 'Prime de sujetion', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1421', 'Indemnite de deplacement', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1431', 'Indemnite d encadrement', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1441', 'Prime de domesticite', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1501', 'Indemnite de transport', 'Semi-auto', 'Gain', FALSE, TRUE, '663800', NULL, 'CI'),
('B', '1601', 'Prime d entretien', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1611', 'Prime d eloignement', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1701', 'Commissions sur vente', 'Semi-auto', 'Gain', FALSE, TRUE, '661100', NULL, 'CI'),
('B', '1751', 'Indemnite de repas', 'Semi-auto', 'Gain', FALSE, TRUE, '663800', NULL, 'CI'),
('B', '1761', 'Prime de risque', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1771', 'Prime de caisse', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1781', 'Prime de bilan', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1791', 'Prime de medaille', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1801', 'Prime de rendement', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1811', 'Prime d assiduite', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1821', 'Indemnite de stage', 'Semi-auto', 'Gain', FALSE, TRUE, '663800', NULL, 'CI'),
('B', '1831', 'Indemnite d interim', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1841', 'Indemnite de mission', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '1851', 'Indemnites forfaitaire', 'Semi-auto', 'Gain', FALSE, TRUE, '663800', NULL, 'CI'),
('B', '1861', 'Prime de froid', 'Semi-auto', 'Gain', FALSE, TRUE, '661200', NULL, 'CI'),
('B', '1871', 'Prime d insalubrite', 'Semi-auto', 'Gain', FALSE, TRUE, '661200', NULL, 'CI'),
('B', '1881', 'Prime de nuit', 'Semi-auto', 'Gain', FALSE, TRUE, '661200', NULL, 'CI'),
('B', '1891', 'Prime d astreinte', 'Semi-auto', 'Gain', FALSE, TRUE, '661200', NULL, 'CI'),
('B', '1901', 'Prime de securite', 'Semi-auto', 'Gain', FALSE, TRUE, '661200', NULL, 'CI'),
('B', '1911', 'Prime d habillement', 'Semi-auto', 'Gain', FALSE, TRUE, '661200', NULL, 'CI'),
('B', '1921', 'Prime sur objectifs / resultats', 'Semi-auto', 'Gain', FALSE, TRUE, '661200', NULL, 'CI'),
('B', '1931', 'Prime encouragement', 'Semi-auto', 'Gain', FALSE, TRUE, '661200', NULL, 'CI'),
('B', '1941', 'Rappel salaire brut', 'Semi-auto', 'Gain', FALSE, TRUE, '661100', NULL, 'CI'),
('B', '2001', 'Indemnites compensatrice de preavis', 'Semi-auto', 'Gain', FALSE, TRUE, '661200', NULL, 'CI'),
('B', '2011', 'Indemnite de licenciement', 'Semi-auto', 'Gain', FALSE, TRUE, '661400', NULL, 'CI'),
('B', '2021', 'Prime de depart a la retraite', 'Semi-auto', 'Gain', FALSE, TRUE, '661400', NULL, 'CI'),
('B', '2031', 'Indemnite d apprentissage', 'Semi-auto', 'Gain', FALSE, TRUE, '663800', NULL, 'CI'),
('B', '2041', 'Indemnites compensatrice de conges payes', 'Semi-auto', 'Gain', FALSE, TRUE, '661300', NULL, 'CI'),
('B', '2051', 'Gratification', 'Semi-auto', 'Gain', FALSE, TRUE, '661200', NULL, 'CI'),
('B', '2061', 'Prime de fin d annee', 'Semi-auto', 'Gain', FALSE, TRUE, '661200', NULL, 'CI'),
('B', '2071', '13eme mois', 'Semi-auto', 'Gain', FALSE, TRUE, '661200', NULL, 'CI'),
('B', '2081', 'Allocation Conges', 'Semi-auto', 'Gain', FALSE, TRUE, '661300', NULL, 'CI'),
('B', '2091', 'Autres primes imposables', 'Semi-auto', 'Gain', FALSE, TRUE, '661200', NULL, 'CI'),
('B', '2101', 'indem forfaitaire de deplacement', 'Semi-auto', 'Gain', FALSE, TRUE, '661800', NULL, 'CI'),
('B', '2121', 'Indemnites de fin de contrat', 'Semi-auto', 'Gain', FALSE, TRUE, '661400', NULL, 'CI'),
('B', '2131', 'Indemnite kilometrique', 'Semi-auto', 'Gain', FALSE, TRUE, '663800', NULL, 'CI'),
('B', '2201', 'Participation', 'Semi-auto', 'Gain', FALSE, TRUE, '663800', NULL, 'CI'),
('B', '2211', 'Interessement', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '2221', 'Actionnariat salarie', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '2231', 'Stock-options', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '2301', 'Prime de permis gros engin', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '2311', 'Augmentation speciale', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '2321', 'Prime de lait', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '2701', 'Retenue pour mise a pied', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '2801', 'Retenue pour absences', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '2811', 'Retenue journaliere pour absence', 'Auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '2821', 'Retenue horaire pour absence', 'Auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '2831', 'Autres retenues sur brut', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '2841', 'Honoraires', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '2851', 'Prime de precarite', 'Auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '2861', 'Prime de precarite', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '2871', 'Ajustement salaire brut', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('B', '2991', 'Frais funeraires', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('A', '3001', 'Autres avantage en nature', 'Semi-auto', 'Gain', FALSE, TRUE, '661700', NULL, 'CI'),
('A', '3051', 'Avantage en nature - Logement et accessoires', 'Semi-auto', 'Gain', FALSE, TRUE, '661700', NULL, 'CI'),
('A', '3061', 'Avantage en nature - Logement et accessoires - Baremes', 'Semi-auto', 'Gain', FALSE, TRUE, '661700', NULL, 'CI'),
('A', '3101', 'Avantage en nature - Domesticite - Reel', 'Semi-auto', 'Gain', FALSE, TRUE, '661700', NULL, 'CI'),
('A', '3111', 'Avantage en nature - Domesticite - Baremes', 'Semi-auto', 'Gain', FALSE, TRUE, '661700', NULL, 'CI'),
('A', '3201', 'Avantage en nature - Vehicule', 'Semi-auto', 'Gain', FALSE, TRUE, '661700', NULL, 'CI'),
('A', '3301', 'Avantage en nature - Nourriture', 'Semi-auto', 'Gain', FALSE, TRUE, '661700', NULL, 'CI'),
('A', '3501', 'Avantage en nature - Outils de communication', 'Semi-auto', 'Gain', FALSE, TRUE, '661700', NULL, 'CI'),
('A', '3601', 'Avantages sociaux - Assurance maladie', 'Semi-auto', 'Gain', FALSE, TRUE, '661700', NULL, 'CI'),
('A', '3611', 'Avantages sociaux - Retraite complementaire', 'Semi-auto', 'Gain', FALSE, TRUE, '661700', NULL, 'CI'),
('I', '4011', 'Impôt sur salaire', 'Auto', 'Retenue', FALSE, TRUE, NULL, '447210', 'CI'),
('I', '4021', 'Contribution Nationale', 'Auto', 'Retenue', FALSE, TRUE, NULL, '447300', 'CI'),
('I', '4031', 'Impôt general sur le revenu', 'Auto', 'Retenue', FALSE, TRUE, NULL, '447100', 'CI'),
('I', '4041', 'Impôt brut sur salaire', 'Auto', 'Retenue', FALSE, TRUE, NULL, '447210', 'CI'),
('I', '4051', 'Reduction d impôt pour charge familiale', 'Auto', 'Retenue', FALSE, TRUE, NULL, '447210', 'CI'),
('I', '4061', 'Retenue BNC', 'Auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('I', '4101', 'Assurance vieillesse CNPS', 'Auto', 'Retenue', FALSE, TRUE, NULL, '431310', 'CI'),
('I', '4111', 'Cotisation CMU part salariale', 'Auto', 'Retenue', FALSE, TRUE, NULL, '431800', 'CI'),
('I', '4121', 'Assurance vieillesse CGRAE', 'Auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('I', '4801', 'Rappel cotisation CMU', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('I', '4811', 'Retenue a la source', 'Auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('I', '4951', 'Regularisation IS', 'Auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('I', '4961', 'Regularisation CN', 'Auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('I', '4971', 'Regularisation IGR', 'Auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('I', '4981', 'Regularisation CNPS', 'Auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('I', '4991', 'Regularisation annuelle IGR', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('NS', '5011', 'Acompte', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, '421100', 'CI'),
('NS', '5021', 'Avances', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('NS', '5031', 'Mensualite prets', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, '421100', 'CI'),
('NS', '5041', 'Domesticite(y compris eau,telephone,electricite)', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('NS', '5051', 'Prime exceptionnelle', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('NS', '5061', 'Pret scolaire', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, '421300', 'CI'),
('NS', '5071', 'Avance sur salaire', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('NS', '5101', 'Cotisations assurance maladie', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('NS', '5111', 'Cotisations mutuelle', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('NS', '5121', 'Autres cotisations', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('NS', '5201', 'Retenue Abonnement', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, '421300', 'CI'),
('NS', '5211', 'Retenues loyer', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, '421300', 'CI'),
('NS', '5221', 'Location vehicule', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('NS', '5231', 'Retenue car plan', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('NS', '5241', 'Retenues divers services', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('NS', '5251', 'Retenue tenue', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('NS', '5261', 'Retenue communication', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('NS', '5271', 'Retenue cantine', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('NS', '5281', 'Retenue MUGEFCI', 'Auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('NS', '5291', 'Trop percu', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('NS', '5301', 'Remboursement frais forfaitaire', 'Semi-auto', 'Gain', FALSE, TRUE, '421300', NULL, 'CI'),
('NS', '5311', 'Forfait entretien vehicule', 'Semi-auto', 'Gain', FALSE, TRUE, '421300', NULL, 'CI'),
('NS', '5351', 'Retenue preavis', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('NS', '5401', 'Dotation telephonique', 'Semi-auto', 'Gain', FALSE, TRUE, '421300', NULL, 'CI'),
('NS', '5411', 'Dotation carburant', 'Semi-auto', 'Gain', FALSE, TRUE, '421300', NULL, 'CI'),
('NS', '5501', 'Pret accorde', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('NS', '5701', 'Regularisation remboursement de frais', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('NS', '5801', 'Regularisation salaire', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('NS', '5811', 'Regularisation prime de stage', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('NS', '5901', 'Retraite complementaire', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('NS', '6001', 'Bonus net d impôt', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('NS', '7501', 'Reprise avantage en nature', 'Auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('NS', '8001', 'Arrondi de paie', 'Auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('NS', '8011', 'Reprise arrondi', 'Auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('NS', '8021', 'Arrondi de paie', 'Semi-auto', 'Gain', FALSE, TRUE, NULL, NULL, 'CI'),
('C', '9011', 'Contribution employeur - Expatrie', 'Auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('C', '9021', 'Contribution employeur - Agricole', 'Auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('C', '9031', 'Contribution nationale', 'Auto', 'Retenue', FALSE, TRUE, '664100', NULL, 'CI'),
('C', '9101', 'Taxe d apprentissage', 'Auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('C', '9111', 'Taxe Formation continue', 'Auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('C', '9201', 'Accident de travail', 'Auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('C', '9211', 'Prestation familiale', 'Auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('C', '9221', 'Assurance maternite', 'Auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('C', '9231', 'Assurance vieillesse', 'Auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('C', '9301', 'Cotisation CMU part patronale', 'Auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('C', '9311', 'Assurance vieillesse CGRAE', 'Auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('C', '9321', 'Autres assurances Maladie', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('C', '9401', 'Retraite complementaire', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI'),
('C', '9501', 'Nourriture', 'Semi-auto', 'Retenue', FALSE, TRUE, NULL, NULL, 'CI');
ON CONFLICT (code, pays) DO UPDATE SET
  libelle = EXCLUDED.libelle,
  type = EXCLUDED.type,
  sens = EXCLUDED.sens,
  date_modification = CURRENT_TIMESTAMP;
