-- ==============================================================================
-- SEED DE LA BASE DE DONNEES PAYOHADA (POSTGRESQL / SQLITE)
-- ==============================================================================

-- 1. Seed de la table constantes
INSERT INTO constantes (code, description, montant, unite, pays) VALUES
('C_NBHTRA_REF', 'NOMBRE D''HEURES TRAVAILLEES DE REFERENCE', 173.33, NULL, 'CI'),
('C_NBJRTRA_REF', 'NOMBRE DE JOURS TRAVAILLES DE REFERENCE', 30.00, NULL, 'CI'),
('CE_EXP_REG_GL', 'Contribution employeur expatrié regime général', 11.50, NULL, 'CI'),
('CE_REG_AG', 'Contribution employeur régime agricole', 2.00, NULL, 'CI'),
('CN_REG_GL', 'Contribution nationale régime général', 1.50, NULL, 'CI'),
('FDFP_TA', 'FDFP Taxe apprentissage', 0.40, NULL, 'CI'),
('FDFP_TFC', 'FDFP Taxe formation continue', 0.60, NULL, 'CI'),
('MAX_MUGEFCI', 'COTISATION MAXIMUM MUGEFCI', 0.00, NULL, 'CI'),
('MOD_CONV_H_J', 'Mode de conversion des heures travaillés en jours', 0.00, NULL, 'CI'),
('MONT_COT_CMU', 'Montant cotisation CMU', 1000.00, NULL, 'CI'),
('PL_LG_INDTRANS', 'Plancher légal de l''indemnité de transport', 30000.00, NULL, 'CI'),
('PL_LG_PRIM_SALI', 'Plancher légal de la prime de salissure', 4500.00, NULL, 'CI'),
('PL_LG_PRIMOUTIL', 'Plancher légal de la prime d''outillage', 3461.00, NULL, 'CI'),
('PL_LG_PRIMTENUE', 'Plancher légal de la prime de tenue de travail', 2423.00, NULL, 'CI'),
('PLF_AT_AM_PF', 'Montant plafond PF, ATMP et AM', 75000.00, NULL, 'CI'),
('PLF_AT_AM_PF_H', 'Montant plafond PF, ATMP et AM Horaire', 433.00, NULL, 'CI'),
('PLF_AT_AM_PF_J', 'Montant plafond PF, ATMP et AM journalier', 3462.00, NULL, 'CI'),
('PLF_AV', 'Montant plafond Assurance vieillesse', 3375000.00, NULL, 'CI'),
('PLF_AV_H', 'Plafond assurance vieillesse horaire', 19472.00, NULL, 'CI'),
('PLF_AV_J', 'Plafond assurance vieillesse journalier', 155772.00, NULL, 'CI'),
('PLF_INDEM_APPR', 'Plafond indemnité d''apprentissage', 100000.00, NULL, 'CI'),
('PLF_INDEM_STAGE', 'Montant plafond indemnité de stage', 150000.00, NULL, 'CI'),
('PLF_JR_HR', 'Montant plafond journalier et horaire', 3231.00, NULL, 'CI'),
('PLF_MUGEFCI', 'PLAFOND MUGEFCI', 0.00, NULL, 'CI'),
('PRIM_LG_PANIER', 'Prime légale de panier', 1038.00, NULL, 'CI'),
('SMIG', 'SMIG mensuel', 75000.00, NULL, 'CI'),
('SMIG_H', 'SMIG horaire', 433.00, NULL, 'CI'),
('SMIG_J', 'SMIG journalier', 3462.00, NULL, 'CI'),
('TAUX_AM', 'Taux assurance maternité', 0.75, NULL, 'CI'),
('TAUX_AT', 'Taux accident de travail', 2.00, NULL, 'CI'),
('TAUX_AV', 'Taux assurance vieillesse', 7.70, NULL, 'CI'),
('TAUX_BNC', 'TAUX_BNC', 3.50, NULL, 'CI'),
('TAUX_CGRAE_E', 'TAUX CGRAE PART EMPLOYE', 8.33, NULL, 'CI'),
('TAUX_CGRAE_P', 'TAUX CGRAE PART PATRONALE', 16.67, NULL, 'CI'),
('TAUX_HS_100', 'TAUX HEURE SUPPLEMENTAIRE 100%', 2.00, NULL, 'CI'),
('TAUX_HS_15', 'TAUX HEURE SUPPLEMENTAIRE 15%', 1.15, NULL, 'CI'),
('TAUX_HS_50', 'TAUX HEURE SUPPLEMENTAIRE 50%', 1.50, NULL, 'CI'),
('TAUX_HS_75', 'TAUX HEURE SUPPLEMENTAIRE 75%', 1.75, NULL, 'CI'),
('TAUX_HS_N', 'TAUX HEURE SUPPLEMENTAIRE NORMALE', 1.00, NULL, 'CI'),
('TAUX_JRSUP_NORM', 'Taux normal jours supplémentaires', 1.00, NULL, 'CI'),
('TAUX_MUGEFCI', 'TAUX DE COTISATION MUGEFCI', 0.00, NULL, 'CI'),
('TAUX_PF', 'Taux prestation familiale', 5.00, NULL, 'CI'),
('TAUX_PRIM_PRECA', 'Taux de la prime de précarité', 5.00, NULL, 'CI'),
('TAUXIS', 'TAUX IS', 1.20, NULL, 'CI'),
('TAUXRET', 'TAUXRET', 6.30, NULL, 'CI'),
('TAXAPP', 'Taxe d''apprentissage', 0.40, NULL, 'CI'),
('TAXFORM', 'Taxe Formation continue', 0.60, NULL, 'CI'),
('VAL_INDICE', 'VALEUR INDICIAIRE', 233.46, NULL, 'CI')
ON CONFLICT (code, pays) DO UPDATE SET
  description = EXCLUDED.description,
  montant = EXCLUDED.montant,
  unite = EXCLUDED.unite,
  date_modification = CURRENT_TIMESTAMP;

-- 2. Seed de la table plan_paie
INSERT INTO plan_paie (code, type, libelle, mode_calcul, sens, pays) VALUES
('BASE', 'B', 'Salaire de base', 'Manuel', 'Gain', 'CI'),
('SURSALAIRE', 'B', 'Sursalaire', 'Manuel', 'Gain', 'CI'),
('ABS', 'B', 'Absence', 'Sémi-auto', 'Retenue', 'CI'),
('HS_15', 'B', 'Heures supplémentaires majorées à 15%', 'Sémi-auto', 'Gain', 'CI'),
('HS_25', 'B', 'Heures supplémentaires majorées à 25%', 'Sémi-auto', 'Gain', 'CI'),
('HS_50', 'B', 'Heures supplémentaires majorées à 50%', 'Sémi-auto', 'Gain', 'CI'),
('IBS', 'I', 'Impôt brut sur salaire', 'Auto', 'Retenue', 'CI'),
('RICF', 'I', 'Réduction d''impôt pour charge familiale', 'Auto', 'Gain', 'CI'),
('CNPS_PF', 'I', 'CNPS - Prestations Familiales', 'Auto', 'Retenue', 'CI'),
('CNPS_RETRAITE', 'I', 'CNPS - Retraite', 'Auto', 'Retenue', 'CI'),
('CNPS_AT', 'I', 'CNPS - Accidents du Travail et Maladies Pro.', 'Auto', 'Retenue', 'CI'),
('CNPS_MATERNITE', 'I', 'CNPS - Assurance Maternité', 'Auto', 'Retenue', 'CI'),
('CMU_S', 'I', 'Cotisation CMU part salariale', 'Auto', 'Retenue', 'CI'),
('CMU_P', 'C', 'Cotisation CMU part patronale', 'Auto', 'Charge', 'CI'),
('CN', 'C', 'Contribution nationale', 'Auto', 'Charge', 'CI'),
('TA', 'C', 'Taxe d''apprentissage', 'Auto', 'Charge', 'CI'),
('TFC', 'C', 'Taxe Formation continue', 'Auto', 'Charge', 'CI'),
('TRANSPORT', 'A', 'Indemnité de transport', 'Sémi-auto', 'Gain', 'CI'),
('TELEPHONE', 'A', 'Dotation téléphonique', 'Sémi-auto', 'Gain', 'CI')
ON CONFLICT (code, pays) DO UPDATE SET
  libelle = EXCLUDED.libelle,
  type = EXCLUDED.type,
  sens = EXCLUDED.sens,
  date_modification = CURRENT_TIMESTAMP;
