"""Initial migration

Revision ID: 834a73d06828
Revises: None
Create Date: 2026-06-08 19:27:36.150487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '834a73d06828'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=True),
    sa.Column('prenom', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('supabase_uid', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_index(op.f('ix_utilisateurs_id'), 'utilisateurs', ['id'], unique=False)
    op.create_index(op.f('ix_utilisateurs_supabase_uid'), 'utilisateurs', ['supabase_uid'], unique=True)
    op.create_table('variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('libelle', sa.String(length=200), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variables_code'), 'variables', ['code'], unique=True)
    op.create_index(op.f('ix_variables_id'), 'variables', ['id'], unique=False)
    op.create_table('dossiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('siret', sa.String(length=14), nullable=True),
    sa.Column('nom_dossier', sa.String(length=50), nullable=False),
    sa.Column('adresse_email', sa.String(length=150), nullable=True),
    sa.Column('telephone', sa.String(length=15), nullable=True),
    sa.Column('nom_contact', sa.String(length=100), nullable=True),
    sa.Column('qualite', sa.Integer(), nullable=True),
    sa.Column('annee', sa.String(length=4), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dossiers_code'), 'dossiers', ['code'], unique=True)
    op.create_index(op.f('ix_dossiers_id'), 'dossiers', ['id'], unique=False)
    op.create_index('ix_dossiers_siret', 'dossiers', ['siret'], unique=False)
    op.create_table('etablissements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('raison_sociale', sa.String(length=200), nullable=False),
    sa.Column('etablissement_principal', sa.Boolean(), nullable=True),
    sa.Column('siret', sa.String(length=14), nullable=True),
    sa.Column('forme_juridique', sa.Integer(), nullable=True),
    sa.Column('civilite', sa.String(length=10), nullable=True),
    sa.Column('activite', sa.String(length=200), nullable=True),
    sa.Column('ape', sa.String(length=5), nullable=True),
    sa.Column('libelle_ape', sa.String(length=200), nullable=True),
    sa.Column('ccn', sa.Integer(), nullable=True),
    sa.Column('ccn2', sa.Integer(), nullable=True),
    sa.Column('ccn3', sa.Integer(), nullable=True),
    sa.Column('ccn4', sa.Integer(), nullable=True),
    sa.Column('ccn5', sa.Integer(), nullable=True),
    sa.Column('avenant', sa.Boolean(), nullable=True),
    sa.Column('numero_cotisant', sa.String(length=18), nullable=True),
    sa.Column('date_radiation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('code_risque_at', sa.String(length=20), nullable=True),
    sa.Column('taux_at', sa.Float(), nullable=True),
    sa.Column('is_taux_versement_transport', sa.Boolean(), nullable=True),
    sa.Column('taux_versement_transport', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dossier_id', 'code', name='uq_etablissement_dossier_code')
    )
    op.create_index(op.f('ix_etablissements_id'), 'etablissements', ['id'], unique=False)
    op.create_index(op.f('ix_etablissements_siret'), 'etablissements', ['siret'], unique=False)
    op.create_table('net_entreprises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('parametrage_domaine', sa.Boolean(), nullable=True),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('siret', sa.String(length=14), nullable=False),
    sa.Column('civilite', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telephone', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dossier_id')
    )
    op.create_index(op.f('ix_net_entreprises_id'), 'net_entreprises', ['id'], unique=False)
    op.create_table('adresses_etablissements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etablissement_id', sa.Integer(), nullable=True),
    sa.Column('adresse_postale', sa.String(length=200), nullable=True),
    sa.Column('adresse_postale2', sa.String(length=200), nullable=True),
    sa.Column('complement_adresse', sa.String(length=200), nullable=True),
    sa.Column('code_postal', sa.String(length=10), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('code_insee', sa.String(length=10), nullable=True),
    sa.Column('code_distribution_etranger', sa.String(length=20), nullable=True),
    sa.Column('pays', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etablissement_id')
    )
    op.create_index(op.f('ix_adresses_etablissements_id'), 'adresses_etablissements', ['id'], unique=False)
    op.create_table('banques_etablissements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etablissement_id', sa.Integer(), nullable=True),
    sa.Column('virement', sa.Boolean(), nullable=True),
    sa.Column('code_bic', sa.String(length=11), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etablissement_id')
    )
    op.create_index(op.f('ix_banques_etablissements_id'), 'banques_etablissements', ['id'], unique=False)
    op.create_table('caisses_cotisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etablissement_id', sa.Integer(), nullable=True),
    sa.Column('nom_caisse', sa.String(length=200), nullable=True),
    sa.Column('code_dsn', sa.String(length=50), nullable=True),
    sa.Column('adresse_caisse', sa.Text(), nullable=True),
    sa.Column('type_cotisation', sa.String(length=50), nullable=False),
    sa.Column('exclus_de_calcul_dsn', sa.Boolean(), nullable=True),
    sa.Column('numero_affiliation', sa.String(length=20), nullable=True),
    sa.Column('type_paiement', sa.String(length=50), nullable=True),
    sa.Column('periodicite_paiement', sa.String(length=50), nullable=True),
    sa.Column('date_paiement', sa.String(length=20), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('bic', sa.String(length=11), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caisses_cotisations_id'), 'caisses_cotisations', ['id'], unique=False)
    op.create_table('dsns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=30), nullable=True),
    sa.Column('contenu_txt', sa.Text(), nullable=True),
    sa.Column('date_envoi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference_envoi', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etablissement_id', 'mois', 'annee', name='uq_dsn_etablissement_periode')
    )
    op.create_index(op.f('ix_dsns_id'), 'dsns', ['id'], unique=False)
    op.create_table('gestion_conges_payes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etablissement_id', sa.Integer(), nullable=True),
    sa.Column('mois_cloture_droits_cp', sa.Integer(), nullable=True),
    sa.Column('report_automatique', sa.Boolean(), nullable=True),
    sa.Column('gestion_absences_heures_bulletins', sa.Boolean(), nullable=True),
    sa.Column('decompte_conges_payes', sa.String(length=50), nullable=True),
    sa.Column('valorisation_conges_payes', sa.String(length=50), nullable=True),
    sa.Column('bloquer_gestion_cp', sa.Boolean(), nullable=True),
    sa.Column('affilie_caisse_conges_payes', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etablissement_id')
    )
    op.create_index(op.f('ix_gestion_conges_payes_id'), 'gestion_conges_payes', ['id'], unique=False)
    op.create_table('salaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.Column('matricule', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('nom_usage', sa.String(length=100), nullable=True),
    sa.Column('civilite', sa.String(length=10), nullable=True),
    sa.Column('date_naissance', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lieu_naissance', sa.String(length=100), nullable=True),
    sa.Column('departement_naissance', sa.String(length=5), nullable=True),
    sa.Column('pays_naissance', sa.String(length=100), nullable=True),
    sa.Column('nationalite', sa.String(length=100), nullable=True),
    sa.Column('numero_securite_sociale', sa.String(length=15), nullable=True),
    sa.Column('adresse', sa.String(length=200), nullable=True),
    sa.Column('adresse2', sa.String(length=200), nullable=True),
    sa.Column('code_postal', sa.String(length=10), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('pays', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telephone', sa.String(length=15), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('bic', sa.String(length=11), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etablissement_id', 'matricule', name='uq_salarie_etablissement_matricule')
    )
    op.create_index(op.f('ix_salaries_id'), 'salaries', ['id'], unique=False)
    op.create_index(op.f('ix_salaries_matricule'), 'salaries', ['matricule'], unique=False)
    op.create_index(op.f('ix_salaries_numero_securite_sociale'), 'salaries', ['numero_securite_sociale'], unique=False)
    op.create_table('contrats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('salarie_id', sa.Integer(), nullable=False),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.Column('code_etablissement', sa.String(length=15), nullable=False),
    sa.Column('matricule_salarie', sa.String(length=50), nullable=False),
    sa.Column('numero_contrat', sa.String(length=50), nullable=False),
    sa.Column('ancien_numero_contrat_dsn', sa.String(length=50), nullable=True),
    sa.Column('emploi_conventionnel', sa.Integer(), nullable=True),
    sa.Column('ccn', sa.Integer(), nullable=True),
    sa.Column('idcc', sa.Integer(), nullable=True),
    sa.Column('emploi', sa.String(length=200), nullable=True),
    sa.Column('type_contrat_travail', sa.Integer(), nullable=False),
    sa.Column('type_contrat_temps_partiel', sa.Integer(), nullable=True),
    sa.Column('statut_professionnel', sa.Integer(), nullable=False),
    sa.Column('regime_retraite', sa.Integer(), nullable=True),
    sa.Column('cas_particuliers', sa.Integer(), nullable=True),
    sa.Column('salaire_mensuel', sa.Float(), nullable=True),
    sa.Column('salaire_horaire', sa.Float(), nullable=True),
    sa.Column('type_salaire', sa.String(length=10), nullable=True),
    sa.Column('nbr_heures_travail_mensuel_majorees', sa.Float(), nullable=True),
    sa.Column('date_debut_contrat', sa.String(length=20), nullable=True),
    sa.Column('date_fin_previsionnelle_contrat', sa.String(length=20), nullable=True),
    sa.Column('date_anciennete', sa.String(length=20), nullable=True),
    sa.Column('salarie_temps_partiel', sa.Boolean(), nullable=True),
    sa.Column('forfait_jour', sa.Boolean(), nullable=True),
    sa.Column('ne_pas_calculer_premier_bulletin', sa.Boolean(), nullable=True),
    sa.Column('nbr_jour_annuels_prevus', sa.Float(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.ForeignKeyConstraint(['salarie_id'], ['salaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dossier_id', 'numero_contrat', name='uq_contrat_dossier_numero')
    )
    op.create_index(op.f('ix_contrats_id'), 'contrats', ['id'], unique=False)
    op.create_table('absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrat_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('date_debut', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nbr_heure_by_user', sa.Float(), nullable=True),
    sa.Column('nbr_jour_by_user', sa.Float(), nullable=True),
    sa.Column('mois', sa.Integer(), nullable=True),
    sa.Column('annee', sa.String(length=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contrat_id'], ['contrats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_absences_contrat_periode', 'absences', ['contrat_id', 'annee', 'mois'], unique=False)
    op.create_index(op.f('ix_absences_id'), 'absences', ['id'], unique=False)
    op.create_table('bulletins_paies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrat_id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=30), nullable=True),
    sa.Column('date_paiement', sa.DateTime(timezone=True), nullable=True),
    sa.Column('salaire_brut', sa.Float(), nullable=True),
    sa.Column('cotisations_salariales', sa.Float(), nullable=True),
    sa.Column('cotisations_patronales', sa.Float(), nullable=True),
    sa.Column('net_a_payer', sa.Float(), nullable=True),
    sa.Column('net_imposable', sa.Float(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('inclure_document_de_sortie', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contrat_id'], ['contrats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contrat_id', 'mois', 'annee', name='uq_bulletin_contrat_periode')
    )
    op.create_index('ix_bulletin_dossier_periode', 'bulletins_paies', ['dossier_id', 'annee', 'mois'], unique=False)
    op.create_index(op.f('ix_bulletins_paies_id'), 'bulletins_paies', ['id'], unique=False)
    op.create_table('departs_salaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrat_id', sa.Integer(), nullable=True),
    sa.Column('date_sortie', sa.String(length=20), nullable=True),
    sa.Column('bulletin_post_contrat', sa.Boolean(), nullable=True),
    sa.Column('bulletin_post_contrat_du', sa.String(length=20), nullable=True),
    sa.Column('bulletin_post_contrat_au', sa.String(length=20), nullable=True),
    sa.Column('motif_sortie', sa.Integer(), nullable=True),
    sa.Column('date_notification_rupture', sa.String(length=20), nullable=True),
    sa.Column('date_notification_signature', sa.String(length=20), nullable=True),
    sa.Column('date_engagement_procedure', sa.String(length=20), nullable=True),
    sa.Column('maintien_affiliation', sa.Boolean(), nullable=True),
    sa.Column('transaction_en_cours', sa.Boolean(), nullable=True),
    sa.Column('dernier_jour_travaille', sa.String(length=20), nullable=True),
    sa.Column('statut_particulier', sa.Integer(), nullable=True),
    sa.Column('type_paiement_preavis01', sa.Integer(), nullable=True),
    sa.Column('preavis_de01', sa.String(length=20), nullable=True),
    sa.Column('preavis_au01', sa.String(length=20), nullable=True),
    sa.Column('type_paiement_preavis02', sa.Integer(), nullable=True),
    sa.Column('preavis_de02', sa.String(length=20), nullable=True),
    sa.Column('preavis_au02', sa.String(length=20), nullable=True),
    sa.Column('type_paiement_preavis03', sa.Integer(), nullable=True),
    sa.Column('preavis_de03', sa.String(length=20), nullable=True),
    sa.Column('preavis_au03', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['contrat_id'], ['contrats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contrat_id')
    )
    op.create_index(op.f('ix_departs_salaries_id'), 'departs_salaries', ['id'], unique=False)
    op.create_table('heures_supplementaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrat_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.Float(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=True),
    sa.Column('annee', sa.String(length=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contrat_id'], ['contrats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heures_supplementaires_id'), 'heures_supplementaires', ['id'], unique=False)
    op.create_index('ix_hs_contrat_periode', 'heures_supplementaires', ['contrat_id', 'annee', 'mois'], unique=False)
    op.create_table('horaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrat_id', sa.Integer(), nullable=True),
    sa.Column('horaire_travail', sa.Float(), nullable=True),
    sa.Column('horaire_hebdo', sa.Float(), nullable=True),
    sa.Column('horaire_lundi', sa.Float(), nullable=True),
    sa.Column('horaire_mardi', sa.Float(), nullable=True),
    sa.Column('horaire_mercredi', sa.Float(), nullable=True),
    sa.Column('horaire_jeudi', sa.Float(), nullable=True),
    sa.Column('horaire_vendredi', sa.Float(), nullable=True),
    sa.Column('horaire_samedi', sa.Float(), nullable=True),
    sa.Column('horaire_dimanche', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['contrat_id'], ['contrats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contrat_id')
    )
    op.create_index(op.f('ix_horaires_id'), 'horaires', ['id'], unique=False)
    op.create_table('jours_hebdomadaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrat_id', sa.Integer(), nullable=True),
    sa.Column('jours_hebdo', sa.Float(), nullable=True),
    sa.Column('jour_lundi', sa.Float(), nullable=True),
    sa.Column('jour_mardi', sa.Float(), nullable=True),
    sa.Column('jour_mercredi', sa.Float(), nullable=True),
    sa.Column('jour_jeudi', sa.Float(), nullable=True),
    sa.Column('jour_vendredi', sa.Float(), nullable=True),
    sa.Column('jour_samedi', sa.Float(), nullable=True),
    sa.Column('jour_dimanche', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['contrat_id'], ['contrats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contrat_id')
    )
    op.create_index(op.f('ix_jours_hebdomadaires_id'), 'jours_hebdomadaires', ['id'], unique=False)
    op.create_table('mois_a_exclure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrat_id', sa.Integer(), nullable=True),
    sa.Column('exclure_janvier', sa.Boolean(), nullable=True),
    sa.Column('exclure_fevrier', sa.Boolean(), nullable=True),
    sa.Column('exclure_mars', sa.Boolean(), nullable=True),
    sa.Column('exclure_avril', sa.Boolean(), nullable=True),
    sa.Column('exclure_mai', sa.Boolean(), nullable=True),
    sa.Column('exclure_juin', sa.Boolean(), nullable=True),
    sa.Column('exclure_juillet', sa.Boolean(), nullable=True),
    sa.Column('exclure_aout', sa.Boolean(), nullable=True),
    sa.Column('exclure_septembre', sa.Boolean(), nullable=True),
    sa.Column('exclure_octobre', sa.Boolean(), nullable=True),
    sa.Column('exclure_novembre', sa.Boolean(), nullable=True),
    sa.Column('exclure_decembre', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['contrat_id'], ['contrats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contrat_id')
    )
    op.create_index(op.f('ix_mois_a_exclure_id'), 'mois_a_exclure', ['id'], unique=False)
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrat_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('valeur', sa.String(length=200), nullable=True),
    sa.Column('valeur_numerique', sa.Float(), nullable=True),
    sa.Column('mois', sa.Integer(), nullable=True),
    sa.Column('annee', sa.String(length=4), nullable=True),
    sa.Column('libelle', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contrat_id'], ['contrats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_options_id'), 'options', ['id'], unique=False)
    op.create_table('primes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrat_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=True),
    sa.Column('annee', sa.String(length=4), nullable=True),
    sa.Column('libelle', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contrat_id'], ['contrats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_primes_id'), 'primes', ['id'], unique=False)
    op.create_table('soldes_tout_compte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrat_id', sa.Integer(), nullable=False),
    sa.Column('date_generation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('indemnite_licenciement', sa.Float(), nullable=True),
    sa.Column('indemnite_conges_payes', sa.Float(), nullable=True),
    sa.Column('indemnite_preavis', sa.Float(), nullable=True),
    sa.Column('indemnite_autre', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('statut', sa.String(length=30), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contrat_id'], ['contrats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contrat_id')
    )
    op.create_index(op.f('ix_soldes_tout_compte_id'), 'soldes_tout_compte', ['id'], unique=False)
    op.create_table('variables_reprise_dossier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrat_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('valeur', sa.Float(), nullable=True),
    sa.Column('libelle', sa.String(length=200), nullable=True),
    sa.Column('annee', sa.String(length=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contrat_id'], ['contrats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variables_reprise_dossier_id'), 'variables_reprise_dossier', ['id'], unique=False)
    op.create_table('lignes_bulletins_paies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bulletin_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('libelle', sa.String(length=200), nullable=True),
    sa.Column('salaire_base', sa.Float(), nullable=True),
    sa.Column('base_s', sa.Float(), nullable=True),
    sa.Column('base_p', sa.Float(), nullable=True),
    sa.Column('taux_s', sa.Float(), nullable=True),
    sa.Column('taux_p', sa.Float(), nullable=True),
    sa.Column('montant_pr', sa.Float(), nullable=True),
    sa.Column('montant_cs', sa.Float(), nullable=True),
    sa.Column('montant_cp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['bulletin_id'], ['bulletins_paies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bulletin_id', 'code', name='uq_ligne_bulletin_code')
    )
    op.create_index('ix_ligne_bulletin_code', 'lignes_bulletins_paies', ['bulletin_id', 'code'], unique=False)
    op.create_index(op.f('ix_lignes_bulletins_paies_id'), 'lignes_bulletins_paies', ['id'], unique=False)
    op.create_table('variables_bulletins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bulletin_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('libelle', sa.String(length=200), nullable=True),
    sa.Column('valeur', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['bulletin_id'], ['bulletins_paies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variables_bulletins_id'), 'variables_bulletins', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variables_bulletins_id'), table_name='variables_bulletins')
    op.drop_table('variables_bulletins')
    op.drop_index(op.f('ix_lignes_bulletins_paies_id'), table_name='lignes_bulletins_paies')
    op.drop_index('ix_ligne_bulletin_code', table_name='lignes_bulletins_paies')
    op.drop_table('lignes_bulletins_paies')
    op.drop_index(op.f('ix_variables_reprise_dossier_id'), table_name='variables_reprise_dossier')
    op.drop_table('variables_reprise_dossier')
    op.drop_index(op.f('ix_soldes_tout_compte_id'), table_name='soldes_tout_compte')
    op.drop_table('soldes_tout_compte')
    op.drop_index(op.f('ix_primes_id'), table_name='primes')
    op.drop_table('primes')
    op.drop_index(op.f('ix_options_id'), table_name='options')
    op.drop_table('options')
    op.drop_index(op.f('ix_mois_a_exclure_id'), table_name='mois_a_exclure')
    op.drop_table('mois_a_exclure')
    op.drop_index(op.f('ix_jours_hebdomadaires_id'), table_name='jours_hebdomadaires')
    op.drop_table('jours_hebdomadaires')
    op.drop_index(op.f('ix_horaires_id'), table_name='horaires')
    op.drop_table('horaires')
    op.drop_index('ix_hs_contrat_periode', table_name='heures_supplementaires')
    op.drop_index(op.f('ix_heures_supplementaires_id'), table_name='heures_supplementaires')
    op.drop_table('heures_supplementaires')
    op.drop_index(op.f('ix_departs_salaries_id'), table_name='departs_salaries')
    op.drop_table('departs_salaries')
    op.drop_index(op.f('ix_bulletins_paies_id'), table_name='bulletins_paies')
    op.drop_index('ix_bulletin_dossier_periode', table_name='bulletins_paies')
    op.drop_table('bulletins_paies')
    op.drop_index(op.f('ix_absences_id'), table_name='absences')
    op.drop_index('ix_absences_contrat_periode', table_name='absences')
    op.drop_table('absences')
    op.drop_index(op.f('ix_contrats_id'), table_name='contrats')
    op.drop_table('contrats')
    op.drop_index(op.f('ix_salaries_numero_securite_sociale'), table_name='salaries')
    op.drop_index(op.f('ix_salaries_matricule'), table_name='salaries')
    op.drop_index(op.f('ix_salaries_id'), table_name='salaries')
    op.drop_table('salaries')
    op.drop_index(op.f('ix_gestion_conges_payes_id'), table_name='gestion_conges_payes')
    op.drop_table('gestion_conges_payes')
    op.drop_index(op.f('ix_dsns_id'), table_name='dsns')
    op.drop_table('dsns')
    op.drop_index(op.f('ix_caisses_cotisations_id'), table_name='caisses_cotisations')
    op.drop_table('caisses_cotisations')
    op.drop_index(op.f('ix_banques_etablissements_id'), table_name='banques_etablissements')
    op.drop_table('banques_etablissements')
    op.drop_index(op.f('ix_adresses_etablissements_id'), table_name='adresses_etablissements')
    op.drop_table('adresses_etablissements')
    op.drop_index(op.f('ix_net_entreprises_id'), table_name='net_entreprises')
    op.drop_table('net_entreprises')
    op.drop_index(op.f('ix_etablissements_siret'), table_name='etablissements')
    op.drop_index(op.f('ix_etablissements_id'), table_name='etablissements')
    op.drop_table('etablissements')
    op.drop_index('ix_dossiers_siret', table_name='dossiers')
    op.drop_index(op.f('ix_dossiers_id'), table_name='dossiers')
    op.drop_index(op.f('ix_dossiers_code'), table_name='dossiers')
    op.drop_table('dossiers')
    op.drop_index(op.f('ix_variables_id'), table_name='variables')
    op.drop_index(op.f('ix_variables_code'), table_name='variables')
    op.drop_table('variables')
    op.drop_index(op.f('ix_utilisateurs_supabase_uid'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_id'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    # ### end Alembic commands ###
